In [1]:
import numpy as np

In [3]:
#this is the way you do a list in python
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
#the way you do a numpy array is with np.array
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.zeros((3,3))
np.ones((5,5))
np.linspace(0,10,100)

In [20]:
#dedicado a la algebra de datos
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(4,4)

array([[0.91044142, 0.55794061, 0.27345923, 0.64257208],
       [0.14423526, 0.9492104 , 0.45969153, 0.75522739],
       [0.44120766, 0.63939484, 0.20931975, 0.34121144],
       [0.74792873, 0.39940547, 0.53073859, 0.65718132]])

In [28]:
#(valor inicio, valor fin,(filas, columnas))
np.random.randint(1,10,(3,3))

array([[9, 3, 7],
       [7, 1, 7],
       [5, 1, 2]])

In [15]:
#borrar


prueba  = np.zeros((5,5))

prueba[2,2] = 5.0
print (prueba)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
arr=np.random.randint(1,10,(5,3))
print (arr)
#shape muestra las filas y columnas
arr.shape

[[8 7 4]
 [1 4 3]
 [9 5 5]
 [2 6 4]
 [9 8 1]]


(5, 3)

In [18]:
#redimensiona un array
arr.reshape(1,15)

array([[8, 7, 4, 1, 4, 3, 9, 5, 5, 2, 6, 4, 9, 8, 1]])

In [11]:
matriz = np.random.randint(1,20,20)
print (matriz)

[ 7  8  4  6 13  7  9 12  9 19 19  6  2  8  5  5  7  7 10 19]


In [13]:
matriz.reshape(4,5)

array([[ 7,  8,  4,  6, 13],
       [ 7,  9, 12,  9, 19],
       [19,  6,  2,  8,  5],
       [ 5,  7,  7, 10, 19]])

In [11]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
parte_arra =arr[1:4]
parte_arra[1] =0
arr

array([0, 1, 0, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_try = arr.copy()
arr_try 

array([0, 1, 0, 3, 4, 5, 6, 7, 8, 9])