In [2]:
import numpy as np

In [3]:
arr =np.linspace(1, 10, 10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
condiciones = arr > 5
condiciones

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[(condiciones)&(arr%2==0)]

array([ 6,  8, 10], dtype=int8)

In [23]:
array = np.random.randint(1, 100,size=(6,5))
array [array %1 ==0]


array([17, 11, 64, 42, 66, 41, 87,  2,  9, 10, 74, 34, 72, 54, 94, 28, 88,
       67, 56, 58, 80, 75, 35,  5, 58, 20, 32, 36, 86, 14])