In [1]:
import numpy as np
lista =[1,2,3,4,5,6,7,8,9,10]
lista *2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
lista = np.linspace(1,10,10)
lista


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
lista *2

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [13]:
 lista +2
 

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [14]:
lista +lista

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [20]:
matriz = lista.reshape(2,5)
matriz2=matriz.copy()

In [30]:
matriz 

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [29]:
#prodducto punto
np.matmul(matriz , matriz2.T)

array([[ 55., 130.],
       [130., 330.]])

In [31]:
#para hacer las misma multiplicación de producto punto se usa el @
matriz @ matriz2.T

array([[ 55., 130.],
       [130., 330.]])