In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [5]:
arr = np.array([1,2,3,4], dtype=np.float64)
arr.dtype

dtype('float64')

In [6]:
arr

array([1., 2., 3., 4.])

In [7]:
arr


array([1., 2., 3., 4.])

In [13]:
arr = np.array(['1','2','3','4'])
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4], dtype=int64)

In [2]:
import numpy as np 

In [3]:
escalar = np.array(42)
print(escalar)
escalar.ndim

42


0

In [4]:
SCALAR = np.array([1,2,3,4  ])
print(SCALAR)
SCALAR.ndim

[1 2 3 4]


1

In [8]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
tensor = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]])
tensor.ndim
print (tensor)

In [42]:
vectordimensiones =np.array([1,2,3], ndmin=10)
print(vectordimensiones)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [39]:
expands  = np.expand_dims(np.array([[1,2,3,4,5,6,7,8,9]]), axis=0)
print(expands)
expands.ndim

[[[1 2 3 4 5 6 7 8 9]]]


3

In [40]:
print(expands,expands.ndim)
expands = np.squeeze(expands)
print(expands,expands.ndim)

[[[1 2 3 4 5 6 7 8 9]]] 3
[1 2 3 4 5 6 7 8 9] 1
