In [9]:
import numpy as np

In [7]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
arr = np.array(lista)
type(arr)


numpy.ndarray

In [11]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz =  np.array (matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[1]

2

In [11]:
arr[0]+arr[1]

3

In [12]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz [1,1]

5

In [21]:
arr [::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [22]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])